src/Entity/Receta.php
<?php

namespace App\Entity;

use App\Repository\RecetaRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=RecetaRepository::class)
 */
class Receta
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nombre_receta;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $dosis;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombreReceta(): ?string
    {
        return $this->nombre_receta;
    }

    public function setNombreReceta(string $nombre_receta): self
    {
        $this->nombre_receta = $nombre_receta;

        return $this;
    }

    public function getDosis(): ?string
    {
        return $this->dosis;
    }

    public function setDosis(string $dosis): self
    {
        $this->dosis = $dosis;

        return $this;
    }
}

src/Form/RecetaType.php
<?php

namespace App\Form;

use App\Entity\Receta;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RecetaType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nombre_receta')
            ->add('dosis')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Receta::class,
        ]);
    }
}

src/Controller/RecetaController.php
<?php

namespace App\Controller;

use App\Entity\Receta;
use App\Form\RecetaType;
use App\Repository\RecetaRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/receta")
 */
class RecetaController extends AbstractController
{
    /**
     * @Route("/", name="receta_index", methods={"GET"})
     */
    public function index(RecetaRepository $recetaRepository): Response
    {
        return $this->render('receta/index.html.twig', [
            'recetas' => $recetaRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="receta_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $recetum = new Receta();
        $form = $this->createForm(RecetaType::class, $recetum);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($recetum);
            $entityManager->flush();

            return $this->redirectToRoute('receta_index');
        }

        return $this->render('receta/new.html.twig', [
            'recetum' => $recetum,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="receta_show", methods={"GET"})
     */
    public function show(Receta $recetum): Response
    {
        return $this->render('receta/show.html.twig', [
            'recetum' => $recetum,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="receta_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Receta $recetum): Response
    {
        $form = $this->createForm(RecetaType::class, $recetum);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('receta_index');
        }

        return $this->render('receta/edit.html.twig', [
            'recetum' => $recetum,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="receta_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Receta $recetum): Response
    {
        if ($this->isCsrfTokenValid('delete'.$recetum->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($recetum);
            $entityManager->flush();
        }

        return $this->redirectToRoute('receta_index');
    }
}

templates/receta/_delete_form.html.twig
<form method="post" action="{{ path('receta_delete', {'id': recetum.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ recetum.id) }}">
    <button class="btn btn-primary" >Eliminar</button>
</form>

templates/receta/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">{{ button_label|default('Guardar') }}</button>
{{ form_end(form) }}

templates/receta/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Receta{% endblock %}

{% block body %}
    <h1>Editar Receta</h1>


    <div class="container">
         <div class="row">
            <div  class="col-lg-2"></div>
            <div  class="col-lg-10">
              <div class="row">
               <div class="col-lg-2">
                {{ include('receta/_delete_form.html.twig') }}
                </div>
               <div class="col-lg-4">
                <a href="{{ path('receta_index') }}">Volver a la lista</a>
               </div>
             </div>
            </div>
        </div>
     </div>

</br>

    <div class="container">
        <div class="row">
          <div  class="col-lg-12">
            {{ include('receta/_form.html.twig', {'button_label': 'Actualizar'}) }}
           </div>
        </div> 
    </div> 
             

{% endblock %}

templates/receta/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Receta index{% endblock %}

{% block body %}
    <h1>Receta index</h1>

    <div class="container">
        <div class="row">
            <div  class="col-lg-9"></div>
            <div class="col-lg-3">
            <a href="{{ path('receta_new') }}">Agregar Receta</a>
            </div>
        </div>
     </div>

    <table class="table table-striped table-bordered table-condensed">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nombre_receta</th>
                <th>Dosis</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
        {% for recetum in recetas %}
            <tr>
                <td>{{ recetum.id }}</td>
                <td>{{ recetum.nombreReceta }}</td>
                <td>{{ recetum.dosis }}</td>
                <td>
                    <a href="{{ path('receta_show', {'id': recetum.id}) }}">Mostrar</a>
                    <a href="{{ path('receta_edit', {'id': recetum.id}) }}">Editar</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

templates/receta/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Receta{% endblock %}

{% block body %}

     <div class="container">
       <div class="row">
            <div  class="col-lg-12"></div>
            <div class="col-lg-6">
            <h1>Crear nueva Receta</h1>
            </div>
               <div class="col-lg-6">
                  <a href="{{ path('receta_index') }}">Volver a la lista</a>
            </div>
        </div>
     </div>

    {{ include('receta/_form.html.twig') }}

{% endblock %}

templates/receta/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Receta{% endblock %}

{% block body %}
    <h1>Receta</h1>

    <div class="container">
         <div class="row">
            <div  class="col-lg-6"></div>
            <div class="col-lg-2">
              {{ include('receta/_delete_form.html.twig') }}
            </div>
               <div class="col-lg-2">
               <a href="{{ path('receta_edit', {'id': recetum.id}) }}">Editar</a>
            </div>
               <div class="col-lg-2">
              <a href="{{ path('consulta_index') }}">Volver a la lista editar</a>
            </div>
        </div>
     </div>
</br>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ recetum.id }}</td>
            </tr>
            <tr>
                <th>Nombre_receta</th>
                <td>{{ recetum.nombreReceta }}</td>
            </tr>
            <tr>
                <th>Dosis</th>
                <td>{{ recetum.dosis }}</td>
            </tr>
        </tbody>
    </table>

{% endblock %}