src/Entity/Paciente.php
<?php

namespace App\Entity;

use App\Repository\PacienteRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PacienteRepository::class)
 */
class Paciente
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nombre_paciente;

    /**
     * @ORM\Column(type="string", length=500)
     */
    private $direccion;

    /**
     * @ORM\Column(type="date")
     */
    private $fecha_nac;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $telefono;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombrePaciente(): ?string
    {
        return $this->nombre_paciente;
    }

    public function setNombrePaciente(string $nombre_paciente): self
    {
        $this->nombre_paciente = $nombre_paciente;

        return $this;
    }

    public function getDireccion(): ?string
    {
        return $this->direccion;
    }

    public function setDireccion(string $direccion): self
    {
        $this->direccion = $direccion;

        return $this;
    }

    public function getFechaNac(): ?\DateTimeInterface
    {
        return $this->fecha_nac;
    }

    public function setFechaNac(\DateTimeInterface $fecha_nac): self
    {
        $this->fecha_nac = $fecha_nac;

        return $this;
    }

    public function getTelefono(): ?string
    {
        return $this->telefono;
    }

    public function setTelefono(string $telefono): self
    {
        $this->telefono = $telefono;

        return $this;
    }
}

src/Form/PacienteType.php
<?php

namespace App\Form;

use App\Entity\Paciente;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PacienteType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nombre_paciente')
            ->add('direccion')
            ->add('fecha_nac')
            ->add('telefono')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Paciente::class,
        ]);
    }
}

src/Controller/PacienteController.php
<?php

namespace App\Controller;

use App\Entity\Paciente;
use App\Form\PacienteType;
use App\Repository\PacienteRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/paciente")
 */
class PacienteController extends AbstractController
{
    /**
     * @Route("/", name="paciente_index", methods={"GET"})
     */
    public function index(PacienteRepository $pacienteRepository): Response
    {
        return $this->render('paciente/index.html.twig', [
            'pacientes' => $pacienteRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="paciente_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $paciente = new Paciente();
        $form = $this->createForm(PacienteType::class, $paciente);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($paciente);
            $entityManager->flush();

            return $this->redirectToRoute('paciente_index');
        }

        return $this->render('paciente/new.html.twig', [
            'paciente' => $paciente,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="paciente_show", methods={"GET"})
     */
    public function show(Paciente $paciente): Response
    {
        return $this->render('paciente/show.html.twig', [
            'paciente' => $paciente,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="paciente_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Paciente $paciente): Response
    {
        $form = $this->createForm(PacienteType::class, $paciente);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('paciente_index');
        }

        return $this->render('paciente/edit.html.twig', [
            'paciente' => $paciente,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="paciente_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Paciente $paciente): Response
    {
        if ($this->isCsrfTokenValid('delete'.$paciente->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($paciente);
            $entityManager->flush();
        }

        return $this->redirectToRoute('paciente_index');
    }
}

templates/paciente/_delete_form.html.twig
<form method="post" action="{{ path('paciente_delete', {'id': paciente.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ paciente.id) }}">
    <button class="btn btn-primary">Eliminar</button>
</form>

templates/paciente/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">{{ button_label|default('Guardar') }}</button>
{{ form_end(form) }}

templates/paciente/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Paciente{% endblock %}

{% block body %}
    <h1>Editar Paciente</h1>


    <div class="container">
         <div class="row">
            <div  class="col-lg-2"></div>
            <div  class="col-lg-10">
              <div class="row">
               <div class="col-lg-2">
                {{ include('paciente/_delete_form.html.twig') }}
                </div>
               <div class="col-lg-4">
                <a href="{{ path('paciente_index') }}">Volver a la lista</a>
               </div>
             </div>
            </div>
        </div>
     </div>

</br>

    <div class="container">
        <div class="row">
          <div  class="col-lg-12">
           {{ include('paciente/_form.html.twig', {'button_label': 'Actualizar'}) }}
           </div>
        </div> 
    </div> 

{% endblock %}

templates/paciente/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Paciente index{% endblock %}

{% block body %}
    <h1>Paciente index</h1>

       <div class="container">
        <div class="row">
            <div  class="col-lg-9"></div>
            <div class="col-lg-3">
             <a href="{{ path('paciente_new') }}">Agregar Paciente</a>
            </div>
        </div>
     </div>

    <table class="table table-striped table-bordered table-condensed">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nombre_paciente</th>
                <th>Direccion</th>
                <th>Fecha_nac</th>
                <th>Telefono</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
        {% for paciente in pacientes %}
            <tr>
                <td>{{ paciente.id }}</td>
                <td>{{ paciente.nombrePaciente }}</td>
                <td>{{ paciente.direccion }}</td>
                <td>{{ paciente.fechaNac ? paciente.fechaNac|date('Y-m-d') : '' }}</td>
                <td>{{ paciente.telefono }}</td>
                <td>
                    <a href="{{ path('paciente_show', {'id': paciente.id}) }}">Mostrar</a>
                    <a href="{{ path('paciente_edit', {'id': paciente.id}) }}">Editar</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

templates/paciente/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Paciente{% endblock %}

{% block body %}
       <div class="container">
       <div class="row">
            <div  class="col-lg-12"></div>
            <div class="col-lg-6">
            <h1>Crear nuevo Paciente</h1>
            </div>
               <div class="col-lg-6">
               <a href="{{ path('paciente_index') }}">Volver a la lista</a>
            </div>
        </div>
     </div>

    {{ include('paciente/_form.html.twig') }}

    
{% endblock %}

templates/paciente/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Paciente{% endblock %}

{% block body %}
    <h1>Paciente</h1>

       <div class="container">
         <div class="row">
            <div  class="col-lg-6"></div>
            <div class="col-lg-2">
             {{ include('paciente/_delete_form.html.twig') }}
            </div>
               <div class="col-lg-2">
               <a href="{{ path('paciente_edit', {'id': paciente.id}) }}">Editar</a>
            </div>
               <div class="col-lg-2">
               <a href="{{ path('paciente_index') }}">Volver a la lista editar</a>
            </div>
        </div>
     </div>
</br>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ paciente.id }}</td>
            </tr>
            <tr>
                <th>Nombre_paciente</th>
                <td>{{ paciente.nombrePaciente }}</td>
            </tr>
            <tr>
                <th>Direccion</th>
                <td>{{ paciente.direccion }}</td>
            </tr>
            <tr>
                <th>Fecha_nac</th>
                <td>{{ paciente.fechaNac ? paciente.fechaNac|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Telefono</th>
                <td>{{ paciente.telefono }}</td>
            </tr>
        </tbody>
    </table>

    
{% endblock %}